import { Category, Product } from './types'

export const categories: Category[] = [
  { id: '1', name: 'Áo Thun', slug: 'ao-thun', icon: '👕', productCount: 1250 },
  { id: '2', name: 'Quần Jean', slug: 'quan-jean', icon: '👖', productCount: 860 },
  { id: '3', name: 'Váy Đầm', slug: 'vay-dam', icon: '👗', productCount: 2100 },
  { id: '4', name: 'Áo Khoác', slug: 'ao-khoac', icon: '🧥', productCount: 540 },
  { id: '5', name: 'Giày Dép', slug: 'giay-dep', icon: '👟', productCount: 1800 },
  { id: '6', name: 'Phụ Kiện', slug: 'phu-kien', icon: '👜', productCount: 3200 },
  { id: '7', name: 'Đồ Thể Thao', slug: 'do-the-thao', icon: '🏃', productCount: 720 },
  { id: '8', name: 'Đồ Lót', slug: 'do-lot', icon: '🩲', productCount: 980 },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Áo Thun Unisex Basic Cotton Thoáng Mát',
    slug: 'ao-thun-unisex-basic-cotton',
    price: 129000,
    originalPrice: 199000,
    discount: 35,
    rating: 4.8,
    reviewCount: 2341,
    soldCount: 15200,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=400&fit=crop',
    ],
    category: 'Áo Thun',
    categorySlug: 'ao-thun',
    brand: 'FashionBasic',
    description:
      'Áo thun unisex chất liệu cotton 100% cao cấp, thoáng mát, thấm hút mồ hôi tốt. Thiết kế basic dễ phối đồ, phù hợp nhiều dịp mặc khác nhau.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Trắng', 'Đen', 'Xám', 'Xanh Navy', 'Đỏ'],
    inStock: true,
    isBestseller: true,
    tags: ['áo thun', 'basic', 'cotton', 'unisex'],
  },
  {
    id: '2',
    name: 'Quần Jean Nữ Skinny Co Giãn 4 Chiều',
    slug: 'quan-jean-nu-skinny-co-gian',
    price: 289000,
    originalPrice: 450000,
    discount: 36,
    rating: 4.7,
    reviewCount: 1876,
    soldCount: 8900,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop',
    ],
    category: 'Quần Jean',
    categorySlug: 'quan-jean',
    brand: 'DenimStyle',
    description:
      'Quần jean nữ skinny chất liệu denim co giãn 4 chiều, ôm dáng tôn đường cong. Độ bền cao, màu sắc không phai.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Xanh Đậm', 'Xanh Nhạt', 'Đen', 'Xám'],
    inStock: true,
    isBestseller: true,
    tags: ['quần jean', 'skinny', 'nữ', 'denim'],
  },
  {
    id: '3',
    name: 'Váy Hoa Nhí Vintage Dáng Xòe Tiểu Thư',
    slug: 'vay-hoa-nhi-vintage-dang-xoe',
    price: 345000,
    originalPrice: 520000,
    discount: 34,
    rating: 4.9,
    reviewCount: 3102,
    soldCount: 21000,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=400&fit=crop',
    ],
    category: 'Váy Đầm',
    categorySlug: 'vay-dam',
    brand: 'VintageCharm',
    description:
      'Váy hoa nhí dáng xòe phong cách vintage tiểu thư. Chất liệu voan mềm mại, thoáng mát. Phù hợp đi chơi, đi biển, dự tiệc nhẹ.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Hoa Hồng', 'Hoa Xanh', 'Hoa Vàng'],
    inStock: true,
    isNew: true,
    tags: ['váy', 'hoa nhí', 'vintage', 'xòe'],
  },
  {
    id: '4',
    name: 'Áo Khoác Bomber Unisex Phong Cách Hàn Quốc',
    slug: 'ao-khoac-bomber-unisex-han-quoc',
    price: 459000,
    originalPrice: 699000,
    discount: 34,
    rating: 4.6,
    reviewCount: 987,
    soldCount: 5600,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1544923246-77307dd654cb?w=400&h=400&fit=crop',
    ],
    category: 'Áo Khoác',
    categorySlug: 'ao-khoac',
    brand: 'KStreet',
    description:
      'Áo khoác bomber unisex phong cách Hàn Quốc. Chất liệu polyester cao cấp, chống gió nhẹ. Thiết kế thời thượng, dễ phối với nhiều outfit.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh Rêu', 'Be', 'Xám'],
    inStock: true,
    isNew: true,
    tags: ['áo khoác', 'bomber', 'hàn quốc', 'unisex'],
  },
  {
    id: '5',
    name: 'Giày Sneaker Nữ Đế Dày Ulzzang Hàn',
    slug: 'giay-sneaker-nu-de-day-ulzzang',
    price: 399000,
    originalPrice: 650000,
    discount: 39,
    rating: 4.7,
    reviewCount: 2543,
    soldCount: 12800,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1514989940723-e8e51635b782?w=400&h=400&fit=crop',
    ],
    category: 'Giày Dép',
    categorySlug: 'giay-dep',
    brand: 'StepStyle',
    description:
      'Giày sneaker nữ đế dày tăng chiều cao 5cm theo phong cách ulzzang Hàn Quốc. Chất liệu da PU cao cấp, đế cao su êm chân.',
    sizes: ['35', '36', '37', '38', '39', '40'],
    colors: ['Trắng', 'Đen', 'Hồng', 'Be'],
    inStock: true,
    isBestseller: true,
    tags: ['giày', 'sneaker', 'nữ', 'ulzzang', 'đế dày'],
  },
  {
    id: '6',
    name: 'Túi Tote Canvas In Họa Tiết Độc Đáo',
    slug: 'tui-tote-canvas-in-hoa-tiet',
    price: 189000,
    originalPrice: 280000,
    discount: 33,
    rating: 4.5,
    reviewCount: 1234,
    soldCount: 7800,
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
    ],
    category: 'Phụ Kiện',
    categorySlug: 'phu-kien',
    brand: 'ArtBag',
    description:
      'Túi tote canvas in họa tiết độc đáo, phong cách nghệ thuật. Chất liệu canvas dày dặn, bền bỉ. Dung tích lớn, tiện lợi cho đi học, đi chơi.',
    sizes: ['One Size'],
    colors: ['Trắng', 'Đen', 'Be', 'Xanh'],
    inStock: true,
    tags: ['túi tote', 'canvas', 'phụ kiện'],
  },
  {
    id: '7',
    name: 'Bộ Đồ Thể Thao Gym Nữ Crop Top + Legging',
    slug: 'bo-do-the-thao-gym-nu-crop-top-legging',
    price: 359000,
    originalPrice: 550000,
    discount: 35,
    rating: 4.8,
    reviewCount: 1876,
    soldCount: 9400,
    images: [
      'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=400&fit=crop',
    ],
    category: 'Đồ Thể Thao',
    categorySlug: 'do-the-thao',
    brand: 'ActiveFit',
    description:
      'Bộ đồ thể thao gym nữ gồm crop top và legging. Chất liệu spandex co giãn 4 chiều, thấm hút mồ hôi tốt. Thiết kế ôm dáng, tôn lên đường cong cơ thể.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh Biển', 'Hồng', 'Tím'],
    inStock: true,
    isNew: true,
    tags: ['đồ thể thao', 'gym', 'legging', 'crop top', 'nữ'],
  },
  {
    id: '8',
    name: 'Áo Sơ Mi Nam Công Sở Slim Fit Không Nhăn',
    slug: 'ao-so-mi-nam-cong-so-slim-fit',
    price: 259000,
    originalPrice: 399000,
    discount: 35,
    rating: 4.6,
    reviewCount: 2109,
    soldCount: 11300,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=400&h=400&fit=crop',
    ],
    category: 'Áo Thun',
    categorySlug: 'ao-thun',
    brand: 'OfficePro',
    description:
      'Áo sơ mi nam công sở dáng slim fit, chất liệu vải không nhăn cao cấp. Phù hợp mặc đi làm, dự tiệc, gặp đối tác. Thiết kế thanh lịch, chuyên nghiệp.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Trắng', 'Xanh Nhạt', 'Xanh Đậm', 'Hồng Nhạt', 'Đen'],
    inStock: true,
    isBestseller: true,
    tags: ['sơ mi', 'nam', 'công sở', 'slim fit'],
  },
  {
    id: '9',
    name: 'Quần Short Kaki Nam Nữ Phong Cách Casual',
    slug: 'quan-short-kaki-nam-nu-casual',
    price: 199000,
    originalPrice: 320000,
    discount: 38,
    rating: 4.5,
    reviewCount: 876,
    soldCount: 6200,
    images: [
      'https://images.unsplash.com/photo-1560060141-827b9f8a9b24?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400&h=400&fit=crop',
    ],
    category: 'Quần Jean',
    categorySlug: 'quan-jean',
    brand: 'CasualWear',
    description:
      'Quần short kaki unisex phong cách casual năng động. Chất liệu kaki cao cấp, mềm mại, thoáng mát. Phù hợp đi chơi, đi biển, hoạt động ngoài trời.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Be', 'Xanh Rêu', 'Nâu', 'Đen', 'Trắng'],
    inStock: true,
    tags: ['quần short', 'kaki', 'casual', 'unisex'],
  },
  {
    id: '10',
    name: 'Đầm Maxi Dài Voan Hoa Đi Biển',
    slug: 'dam-maxi-dai-voan-hoa-di-bien',
    price: 289000,
    originalPrice: 450000,
    discount: 36,
    rating: 4.9,
    reviewCount: 3456,
    soldCount: 18700,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&h=400&fit=crop',
    ],
    category: 'Váy Đầm',
    categorySlug: 'vay-dam',
    brand: 'BeachStyle',
    description:
      'Đầm maxi dài chất liệu voan hoa nhí, nhẹ nhàng bay bổng. Phù hợp đi biển, resort, dạo phố. Thiết kế dây trễ vai, sexy và nữ tính.',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Hoa Đỏ', 'Hoa Xanh', 'Hoa Vàng'],
    inStock: true,
    isBestseller: true,
    tags: ['đầm maxi', 'voan', 'đi biển', 'nữ'],
  },
  {
    id: '11',
    name: 'Hoodie Nỉ Bông Dày Dặn Unisex Mùa Đông',
    slug: 'hoodie-ni-bong-day-dan-unisex',
    price: 389000,
    originalPrice: 580000,
    discount: 33,
    rating: 4.7,
    reviewCount: 1543,
    soldCount: 8900,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&h=400&fit=crop',
    ],
    category: 'Áo Khoác',
    categorySlug: 'ao-khoac',
    brand: 'WarmWear',
    description:
      'Hoodie nỉ bông dày dặn giữ ấm tốt cho mùa đông. Chất liệu nỉ bông cao cấp, mềm mại, không xù. Thiết kế unisex năng động, có túi kangaroo tiện lợi.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Xám', 'Đen', 'Trắng', 'Xanh Navy', 'Đỏ Đô'],
    inStock: true,
    tags: ['hoodie', 'nỉ bông', 'mùa đông', 'unisex'],
  },
  {
    id: '12',
    name: 'Giày Sandal Nữ Đế Xuồng Đi Biển',
    slug: 'giay-sandal-nu-de-xuong-di-bien',
    price: 299000,
    originalPrice: 480000,
    discount: 38,
    rating: 4.6,
    reviewCount: 987,
    soldCount: 5400,
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400&h=400&fit=crop',
    ],
    category: 'Giày Dép',
    categorySlug: 'giay-dep',
    brand: 'SummerStep',
    description:
      'Giày sandal nữ đế xuồng tăng chiều cao 7cm, phong cách boho chic. Chất liệu da PU mềm mại, quai cài chắc chắn. Phù hợp đi biển, dạo phố mùa hè.',
    sizes: ['35', '36', '37', '38', '39'],
    colors: ['Be', 'Nâu', 'Trắng'],
    inStock: true,
    isNew: true,
    tags: ['sandal', 'nữ', 'đế xuồng', 'đi biển'],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isBestseller).slice(0, 8)
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew).slice(0, 8)
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(price)
}
